-- schema.sql
-- Relational schema for inventory management system

CREATE TABLE Supplier (
  ID_Supplier INT AUTO_INCREMENT PRIMARY KEY,
  Nama_Supplier VARCHAR(100) NOT NULL,
  Kontak_Supplier VARCHAR(50),
  Alamat_Supplier VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE Barang (
  ID_Barang INT AUTO_INCREMENT PRIMARY KEY,
  ID_Supplier INT NOT NULL,
  Nama_Barang VARCHAR(150) NOT NULL,
  Kategori VARCHAR(50),
  Deskripsi TEXT,
  Harga_Satuan DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  Satuan VARCHAR(20) NOT NULL,
  FOREIGN KEY (ID_Supplier) REFERENCES Supplier(ID_Supplier)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;
 DFFFBNBDKKK
CREATE TABLE Gudang (
  ID_Gudang INT AUTO_INCREMENT PRIMARY KEY,
  Nama_Gudang VARCHAR(100) NOT NULL,
  Lokasi VARCHAR(150),
  Kapasitas INT,
  Jenis_Gudang VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE Toko (
  ID_Toko INT AUTO_INCREMENT PRIMARY KEY,
  Nama_Toko VARCHAR(100) NOT NULL,
  Lokasi_Toko VARCHAR(150),
  Manager_Toko VARCHAR(100),
  Kontak_Toko VARCHAR(50)
) ENGINE=InnoDB;

CREATE TABLE Stok (
  ID_Barang INT NOT NULL,
  ID_Gudang INT NOT NULL,
  ID_Toko INT NOT NULL,
  Jumlah_Stok INT NOT NULL DEFAULT 0,
  Stok_Minimal INT NOT NULL DEFAULT 0,
  Tanggal_Update DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (ID_Barang, ID_Gudang, ID_Toko),
  FOREIGN KEY (ID_Barang) REFERENCES Barang(ID_Barang)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (ID_Gudang) REFERENCES Gudang(ID_Gudang)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (ID_Toko) REFERENCES Toko(ID_Toko)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE Transaksi_Inventaris (
  ID_Transaksi INT AUTO_INCREMENT PRIMARY KEY,
  ID_Barang INT NOT NULL,
  ID_Gudang INT NOT NULL,
  ID_Toko INT NOT NULL,
  Tanggal_Transaksi DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Jenis_Transaksi ENUM('Masuk','Keluar') NOT NULL,
  Jumlah_Transaksi INT NOT NULL,
  Keterangan VARCHAR(255),
  FOREIGN KEY (ID_Barang) REFERENCES Barang(ID_Barang)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (ID_Gudang) REFERENCES Gudang(ID_Gudang)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (ID_Toko) REFERENCES Toko(ID_Toko)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE Distribusi_Barang (
  ID_Distribusi INT AUTO_INCREMENT PRIMARY KEY,
  ID_Transaksi INT NOT NULL,
  ID_Gudang INT NOT NULL,
  ID_Toko INT NOT NULL,
  Tanggal_Distribusi DATETIME NOT NULL,
  Sumber_Lokasi VARCHAR(100) NOT NULL,
  Tujuan_Lokasi VARCHAR(100) NOT NULL,
  Status_Distribusi ENUM('Proses','Selesai') NOT NULL,
  FOREIGN KEY (ID_Transaksi) REFERENCES Transaksi_Inventaris(ID_Transaksi)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (ID_Gudang) REFERENCES Gudang(ID_Gudang)
    ON UPDAT,.E CASCADE ON DELETE RESTRICT,
  FOREIGN KEY (ID_Toko) REFERENCES Toko(ID_Toko)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE Pengguna (
  ID_Pengguna INT AUTO_INCREMENT PRIMARY KEY,
  Nama_Lengkap VARCHAR(150) NOT NULL,
  Email VARCHAR(100) NOT NULL UNIQUE,
  Kata_Sandi VARCHAR(255) NOT NULL,
  Nomor_Telepon VARCHAR(20)
) ENGINE=InnoDB;

CREATE TABLE Performa_Toko (
  ID_Performa INT AUTO_INCREMENT PRIMARY KEY,
  ID_Toko INT NOT NULL,
  Rating TINYINT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
  Tanggal_Feedback DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (ID_Toko) REFERENCES Toko(ID_Toko)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;
